name: Phase1 instance deploy by terraform

on:
 push:
    branches:
        - master

env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    TF_VAR_ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY}}
    SSH_PRIVATE_KEY_BASE64: ${{ secrets.SSH_PRIVATE_KEY_BASE64}}

jobs:
 terraform:
    name: Terraform apply EC2
    runs-on: ubuntu-latest

    defaults:
        run:
         working-directory: infra/terraform

    steps:
        - name: Checkout Code
          uses: actions/checkout@v4
        
        - name: Set up Terraform
          uses: hashicorp/setup-terraform@v3
          with:
            terraform_version: 1.6.6

        - name: Terraform Init & Plan
          run: terraform init & terraform plan
          working-directory: ./infra/terraform

        - name: Terraform Apply
          run: terraform apply -auto-approve
          working-directory: ./infra/terraform

        - name: Show SSH Command Output
          run: terraform output ssh_command
          working-directory: ./infra/terraform



    