name: Deploy to Prod
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.1.0
        with: 
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          port: 22
          timeout: 60
          script: "cd /home/ubuntu/devops && ./deploy.sh"
        
        
