name: Deploy to Prod
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Git-permission
        run: sudo chmod -R 755 .git
      - name: Verify permissions of .git directory
        run: ls -la .git
      - name: Remove and reinitialize .git directory (last resort)
        run: |
          sudo rm -rf .git
          git init
          git remote add origin git@github.com:thantsinmoe/laravel-todo-tsm.git
          git fetch origin
          git reset --hard origin/main
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          debug: true
          script: "cd /var/www/laravel-todo-tsm && ./deploy.sh"
        
        
